apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base and backup base
bases:
  - ../../base
  - ./backup

# Namespace for production
namespace: production

# Namespace resource
resources:
  - namespace.yaml

# Image updates for production
images:
  - name: duonghoang711/todo-app
    newTag: "2.7"
  - name: duonghoang711/todo-backend
    newTag: "2.12"
  - name: duonghoang711/random-todo-cronjob
    newTag: "latest"
  - name: duonghoang711/broadcaster
    newTag: "v2"

# Labels applied by overlay
commonLabels:
  environment: production
  managed-by: kustomize

# Increase broadcaster replicas for production
replicas:
  - name: broadcaster
    count: 2

# Patches for production
patches:
  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: image-pvc
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: standard-rwo
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: todo-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "http://todo-backend-service/todos"


