apiVersion: v1
kind: Service
metadata:
  name: ping-pong-loadbalancer
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
