apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-todo
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: random-todo-job
            image: duonghoang711/random-todo-cronjob:2.9
            env:
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-service.project/todos"
          restartPolicy: OnFailure
