apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: exercises
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS pingpong (
      id SERIAL PRIMARY KEY,
      counter INTEGER NOT NULL
    );
    INSERT INTO pingpong (counter) VALUES (0);
