apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  information.txt: "Kubernetes Exercise 3.2: Ingress with log-output and ping-pong"
  MESSAGE: "Hello from GKE Ingress!"
